schema-version: v2
kind: action
metadata:
  name: lets-go
  display-name: lets-go
  description: Action para stackspot para instalar o go em ambiente local e de produção (Let's go)
  version: 0.0.1
spec:
  type: shell
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  repository: https://github.com/silastgoes/stackspot-lets-go.git
  inputs:
    - label: Qual versão do go deseja instalar?
      name: go-version
      type: text
      required: true
      pattern: '([1-9\.]+)+'
      default: "1.21.5"
  shell:
    workdir: .
    script: 
      linux: |
        export GO_VERSION={{go-version}} # Versão do Go a ser instalada
        check_go_installed() {
        if command -v go >/dev/null  2>&1; then
          echo "Go está instalado."
          return  0
          else
            echo "Go não está instalado."
            return  1
          fi
        }

        # Função para obter a versão atual do Go
        get_current_go_version() {
          if check_go_installed; then
            go version | awk '{print $3}' | tr -d 'go'
          else
            echo "N/A"
          fi
        }

        # Função para instalar o Go
        install_go() {
          echo "Instalando Go versão $GO_VERSION no Linux..."
          apt-get update
          apt-get install -y wget
          wget https://dl.google.com/go/go$GO_VERSION.linux-amd64.tar.gz
          if [ $? -ne   0 ]; then
            echo "Falha ao baixar o Go$GO_VERSION. Verifique o URL e tente novamente."
            return   1
          fi
          tar -xvf go$GO_VERSION.linux-amd64.tar.gz
          mv go /usr/local
        }


        # Verificar se o Go está instalado e obter a versão atual
        if check_go_installed; then
          CURRENT_GO_VERSION=$(get_current_go_version)
          echo "Versão atual do Go: $CURRENT_GO_VERSION"

          # Verificar se a versão atual é diferente da versão desejada
          if [ "$CURRENT_GO_VERSION" != "$GO_VERSION" ]; then
            echo "A versão atual do Go é diferente da versão desejada. Instalando a nova versão..."
            install_go
          else
            echo "A versão atual do Go já é a versão desejada."
          fi
        else
          echo "O Go não está instalado. Instalando a versão desejada..."
          install_go
        fi
